pub const ARTICLES_GROUPS: &[crate::article::EducationArticle] = &[
    crate::article::EducationArticle {
        id: "net/tcp.TCPRetransSegs_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "TCP Retransmissions Distribution",
        title_ja: "TCP再送分布",
        body_en: "What is this?\nA grouped article for retransmission counters that should be read as a distribution: min, max, count, and related buckets.\n\nWhy it matters\nA single spike can be harmless, but repeated retransmits point to loss, congestion, or path instability.\n\nHow to read\n- count: how often retransmits happen\n- max: the worst burst or peak window\n- min: the quiet baseline\n\nCommon mistake\nChecking only the peak and missing whether the pattern is persistent.\n",
        body_ja: "これは何か\n再送カウンタを分布として読むためのグループ記事です。min, max, count と関連バケットをまとめて確認します。\n\nなぜ重要か\n単発のスパイクは問題ないこともありますが、再送が繰り返されるなら損失、輻輳、経路不安定を疑います。\n\nどう読むか\n- count: 再送の発生回数\n- max: 最悪バーストやピーク\n- min: 静かな基準値\n\nよくある誤解\nピークだけを見て、継続的な問題を見逃すことです。\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "TCPRetransSegs min",
                label_ja: "TCPRetransSegs 最小",
                source: "net/tcp",
                field: "TCPRetransSegsMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "TCPRetransSegs max",
                label_ja: "TCPRetransSegs 最大",
                source: "net/tcp",
                field: "TCPRetransSegsMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "TCPRetransSegs count",
                label_ja: "TCPRetransSegs 件数",
                source: "net/tcp",
                field: "TCPRetransSegsCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "net/tcp.TCPRto_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "TCP RTO Distribution",
        title_ja: "TCP RTO 分布",
        body_en: "What is this?\nA grouped article for TCP retransmission timeout values, best read through min/max/count and bucketed ranges.\n\nWhy it matters\nA widening timeout distribution usually means the network path is getting slower or more variable.\n\nHow to read\n- count: how many timeout samples were seen\n- max: worst observed timeout\n- buckets: whether the tail is getting heavier\n",
        body_ja: "これは何か\nTCP再送タイムアウト値を、min/max/count とバケットで読むためのグループ記事です。\n\nなぜ重要か\n分布が広がると、経路が遅くなるか、ばらつきが増えている可能性があります。\n\nどう読むか\n- count: 何回サンプルが出たか\n- max: 観測された最悪値\n- buckets: 尾部が重くなっていないか\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "TCPRto min",
                label_ja: "TCPRto 最小",
                source: "net/tcp",
                field: "TCPRtoMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "TCPRto max",
                label_ja: "TCPRto 最大",
                source: "net/tcp",
                field: "TCPRtoMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "TCPRto count",
                label_ja: "TCPRto 件数",
                source: "net/tcp",
                field: "TCPRtoCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "net/tcp.TCPLatency_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "TCP Latency Distribution",
        title_ja: "TCP遅延分布",
        body_en: "What is this?\nA grouped article for end-to-end TCP latency measurements with min/max/count and percentile-like buckets.\n\nWhy it matters\nLatency distribution shows user impact better than a single average.\n\nHow to read\n- count: sample volume\n- min: best case path\n- max: tail latency and stalls\n",
        body_ja: "これは何か\nTCPのエンドツーエンド遅延を、min/max/count とパーセンタイル風バケットで読むためのグループ記事です。\n\nなぜ重要か\n平均値よりも、遅延分布のほうが体感影響をよく表します。\n\nどう読むか\n- count: サンプル量\n- min: 最良ケース\n- max: 尾部遅延や停滞\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "TCPLatency min",
                label_ja: "TCPLatency 最小",
                source: "net/tcp",
                field: "TCPLatencyMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "TCPLatency max",
                label_ja: "TCPLatency 最大",
                source: "net/tcp",
                field: "TCPLatencyMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "TCPLatency count",
                label_ja: "TCPLatency 件数",
                source: "net/tcp",
                field: "TCPLatencyCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "net/tcp.TCPSendQueue_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "TCP Send Queue Distribution",
        title_ja: "TCP送信キュー分布",
        body_en: "What is this?\nA grouped article for send queue occupancy, useful when the queue is usually empty but occasionally builds up sharply.\n\nWhy it matters\nA long tail in the send queue often means congestion, pacing issues, or an overloaded peer.\n\nHow to read\n- count: number of samples\n- max: worst queue buildup\n- min: baseline queue occupancy\n",
        body_ja: "これは何か\n送信キューの占有分布を読むためのグループ記事です。普段は空でも、時々大きく膨らむケースを見ます。\n\nなぜ重要か\n送信キューの長い尾は、輻輳、送出制御の問題、相手先の過負荷を示すことがあります。\n\nどう読むか\n- count: サンプル数\n- max: 最悪のキュー膨張\n- min: 基準占有量\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "SendQueue min",
                label_ja: "送信キュー 最小",
                source: "net/tcp",
                field: "SendQueueMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "SendQueue max",
                label_ja: "送信キュー 最大",
                source: "net/tcp",
                field: "SendQueueMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "SendQueue count",
                label_ja: "送信キュー 件数",
                source: "net/tcp",
                field: "SendQueueCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "net/tcp.TCPRecvQueue_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "TCP Receive Queue Distribution",
        title_ja: "TCP受信キュー分布",
        body_en: "What is this?\nA grouped article for receive queue depth, especially useful when traffic is bursty.\n\nWhy it matters\nPersistent receive queue growth can point to application backpressure or slow consumers.\n\nHow to read\n- count: how many observations exist\n- max: highest backlog depth\n- buckets: whether spikes are isolated or repeated\n",
        body_ja: "これは何か\n受信キュー深さを読むためのグループ記事です。バースト性のある通信で特に有効です。\n\nなぜ重要か\n受信キューが増え続ける場合、アプリ側の背圧や消費遅延が疑われます。\n\nどう読むか\n- count: 観測数\n- max: 最大バックログ深さ\n- buckets: スパイクが単発か反復か\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "RecvQueue min",
                label_ja: "受信キュー 最小",
                source: "net/tcp",
                field: "RecvQueueMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "RecvQueue max",
                label_ja: "受信キュー 最大",
                source: "net/tcp",
                field: "RecvQueueMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "RecvQueue count",
                label_ja: "受信キュー 件数",
                source: "net/tcp",
                field: "RecvQueueCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "net/tcp.TCPBacklog_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "TCP Backlog Distribution",
        title_ja: "TCPバックログ分布",
        body_en: "What is this?\nA grouped article for accept backlog and related queued connection classes.\n\nWhy it matters\nA backlog that spends time near its maximum means the listener is falling behind incoming traffic.\n\nHow to read\n- count: sample count\n- max: peak backlog pressure\n- min: idle baseline\n",
        body_ja: "これは何か\naccept backlog と関連する待ち接続クラスをまとめて読むためのグループ記事です。\n\nなぜ重要か\n最大値付近に張り付く backlog は、受信側が到着処理に追いついていないサインです。\n\nどう読むか\n- count: サンプル数\n- max: 最大バックログ圧力\n- min: 低負荷時の基準値\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "Backlog min",
                label_ja: "バックログ 最小",
                source: "net/tcp",
                field: "BacklogMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "Backlog max",
                label_ja: "バックログ 最大",
                source: "net/tcp",
                field: "BacklogMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "Backlog count",
                label_ja: "バックログ 件数",
                source: "net/tcp",
                field: "BacklogCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "net/tcp.TCPSynBacklog_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "TCP SYN Backlog Distribution",
        title_ja: "TCP SYNバックログ分布",
        body_en: "What is this?\nA grouped article for half-open connection pressure during SYN intake.\n\nWhy it matters\nRising SYN backlog values can indicate connection floods, capacity limits, or delayed handshakes.\n\nHow to read\n- count: how many samples were recorded\n- max: worst backlog saturation\n- buckets: whether the issue is sharp or sustained\n",
        body_ja: "これは何か\nSYN受付時の半開接続圧力を読むためのグループ記事です。\n\nなぜ重要か\nSYN backlog の上昇は、接続洪水、容量限界、ハンドシェイク遅延の兆候です。\n\nどう読むか\n- count: 計測数\n- max: 最悪の飽和度\n- buckets: 急性か持続か\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "SynBacklog min",
                label_ja: "SYNバックログ 最小",
                source: "net/tcp",
                field: "SynBacklogMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "SynBacklog max",
                label_ja: "SYNバックログ 最大",
                source: "net/tcp",
                field: "SynBacklogMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "SynBacklog count",
                label_ja: "SYNバックログ 件数",
                source: "net/tcp",
                field: "SynBacklogCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "schedstat.runqueue_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "Runqueue Distribution",
        title_ja: "実行キュー分布",
        body_en: "What is this?\nA grouped article for runqueue depth and scheduling pressure statistics.\n\nWhy it matters\nA large runqueue distribution means tasks are ready to run, but CPU time is not keeping up.\n\nHow to read\n- count: sample volume\n- max: worst queue depth\n- buckets: whether contention is brief or constant\n",
        body_ja: "これは何か\n実行キュー深さとスケジューリング圧力の統計をまとめるグループ記事です。\n\nなぜ重要か\nrunqueue の分布が大きいほど、実行可能なタスクに対して CPU 時間が足りません。\n\nどう読むか\n- count: サンプル量\n- max: 最悪のキュー深さ\n- buckets: 競合が一時的か継続的か\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "runqueue min",
                label_ja: "実行キュー 最小",
                source: "schedstat",
                field: "runqueueMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "runqueue max",
                label_ja: "実行キュー 最大",
                source: "schedstat",
                field: "runqueueMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "runqueue count",
                label_ja: "実行キュー 件数",
                source: "schedstat",
                field: "runqueueCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "schedstat.context_switch_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "Context Switch Distribution",
        title_ja: "コンテキストスイッチ分布",
        body_en: "What is this?\nA grouped article for context switch counts and their spread over time.\n\nWhy it matters\nToo many switches can mean lock contention, short-lived work, or scheduler churn.\n\nHow to read\n- count: event volume\n- max: bursty switching peaks\n- min: quiet baseline\n",
        body_ja: "これは何か\nコンテキストスイッチ回数の広がりを読むためのグループ記事です。\n\nなぜ重要か\nスイッチが多すぎると、ロック競合、短命タスク、スケジューラの揺れを示すことがあります。\n\nどう読むか\n- count: 発生量\n- max: バーストピーク\n- min: 静かな基準\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "context switches min",
                label_ja: "コンテキストスイッチ 最小",
                source: "stat",
                field: "contextSwitchesMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "context switches max",
                label_ja: "コンテキストスイッチ 最大",
                source: "stat",
                field: "contextSwitchesMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "context switches count",
                label_ja: "コンテキストスイッチ 件数",
                source: "stat",
                field: "contextSwitchesCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "diskstats.read_wait_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "Disk Read Wait Distribution",
        title_ja: "ディスク読込待ち分布",
        body_en: "What is this?\nA grouped article for disk read wait times, including min/max/count and buckets for tail latency.\n\nWhy it matters\nRead wait distributions reveal storage stalls better than raw throughput.\n\nHow to read\n- count: sample count\n- max: worst read stall\n- buckets: whether long waits are frequent\n",
        body_ja: "これは何か\nディスク読込待ち時間を、min/max/count と尾部バケットで読むためのグループ記事です。\n\nなぜ重要か\n読込待ち分布は、単純なスループットよりもストレージ停滞を示します。\n\nどう読むか\n- count: サンプル数\n- max: 最悪の読込停止\n- buckets: 長い待ちが多いか\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "read wait min",
                label_ja: "読込待ち 最小",
                source: "diskstats",
                field: "readWaitMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "read wait max",
                label_ja: "読込待ち 最大",
                source: "diskstats",
                field: "readWaitMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "read wait count",
                label_ja: "読込待ち 件数",
                source: "diskstats",
                field: "readWaitCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "diskstats.write_wait_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "Disk Write Wait Distribution",
        title_ja: "ディスク書込待ち分布",
        body_en: "What is this?\nA grouped article for disk write wait times, especially useful when flushes or fsyncs create spikes.\n\nWhy it matters\nWrite wait tails correlate with user-visible save delays and I/O queueing.\n\nHow to read\n- count: sample volume\n- max: worst wait\n- min: baseline latency\n",
        body_ja: "これは何か\nディスク書込待ち時間を読むためのグループ記事です。flush や fsync がスパイクを作る場面で有効です。\n\nなぜ重要か\n書込待ちの尾部は、保存遅延や I/O キュー滞留と関係します。\n\nどう読むか\n- count: サンプル量\n- max: 最悪の待ち\n- min: 基本遅延\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "write wait min",
                label_ja: "書込待ち 最小",
                source: "diskstats",
                field: "writeWaitMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "write wait max",
                label_ja: "書込待ち 最大",
                source: "diskstats",
                field: "writeWaitMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "write wait count",
                label_ja: "書込待ち 件数",
                source: "diskstats",
                field: "writeWaitCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "diskstats.io_queue_depth_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "IO Queue Depth Distribution",
        title_ja: "IOキュー深さ分布",
        body_en: "What is this?\nA grouped article for storage queue depth samples across time.\n\nWhy it matters\nQueue depth is a direct signal of whether the device is keeping up with demand.\n\nHow to read\n- count: observations\n- max: peak device queueing\n- buckets: whether saturation is rare or regular\n",
        body_ja: "これは何か\nストレージのキュー深さサンプルを時系列で読むためのグループ記事です。\n\nなぜ重要か\nキュー深さは、装置が需要に追いついているかを直接示します。\n\nどう読むか\n- count: 観測数\n- max: ピーク時のキュー滞留\n- buckets: 飽和が稀か常態か\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "IO queue min",
                label_ja: "IOキュー 最小",
                source: "diskstats",
                field: "ioQueueMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "IO queue max",
                label_ja: "IOキュー 最大",
                source: "diskstats",
                field: "ioQueueMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "IO queue count",
                label_ja: "IOキュー 件数",
                source: "diskstats",
                field: "ioQueueCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "pressure.cpu_stall_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "CPU Stall Distribution",
        title_ja: "CPU停滞分布",
        body_en: "What is this?\nA grouped article for CPU stall samples, useful when runnable work exists but execution is delayed.\n\nWhy it matters\nCPU stall distributions capture scheduler pressure and contention better than a single average.\n\nHow to read\n- count: sample count\n- max: worst stall\n- buckets: whether stalls are brief or sustained\n",
        body_ja: "これは何か\n実行可能な仕事があるのに実行が遅れる、CPU停滞サンプルを読むためのグループ記事です。\n\nなぜ重要か\nCPU停滞分布は、単一平均よりもスケジューラ圧力や競合をよく示します。\n\nどう読むか\n- count: サンプル数\n- max: 最悪の停滞\n- buckets: 一時的か継続的か\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "cpu stall min",
                label_ja: "CPU停滞 最小",
                source: "pressure",
                field: "cpuStallMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "cpu stall max",
                label_ja: "CPU停滞 最大",
                source: "pressure",
                field: "cpuStallMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "cpu stall count",
                label_ja: "CPU停滞 件数",
                source: "pressure",
                field: "cpuStallCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "pressure.memory_stall_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "Memory Stall Distribution",
        title_ja: "メモリ停滞分布",
        body_en: "What is this?\nA grouped article for memory stall samples and tail behavior.\n\nWhy it matters\nMemory stalls show when tasks are blocked on allocation, reclaim, or swap-related delays.\n\nHow to read\n- count: observations\n- max: worst memory stall\n- buckets: whether delay is spreading across the workload\n",
        body_ja: "これは何か\nメモリ停滞サンプルと尾部挙動を読むためのグループ記事です。\n\nなぜ重要か\nメモリ停滞は、割り当て、回収、スワップ関連遅延でタスクが止まる様子を示します。\n\nどう読むか\n- count: 観測数\n- max: 最悪のメモリ停滞\n- buckets: 遅延が全体へ広がっているか\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "memory stall min",
                label_ja: "メモリ停滞 最小",
                source: "pressure",
                field: "memoryStallMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "memory stall max",
                label_ja: "メモリ停滞 最大",
                source: "pressure",
                field: "memoryStallMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "memory stall count",
                label_ja: "メモリ停滞 件数",
                source: "pressure",
                field: "memoryStallCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "pressure.io_stall_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "IO Stall Distribution",
        title_ja: "IO停滞分布",
        body_en: "What is this?\nA grouped article for IO stall times, often used to read contention against storage and filesystem activity.\n\nWhy it matters\nIO stall tails are the clearest user-facing signal that storage is backing up.\n\nHow to read\n- count: sample count\n- max: worst stall window\n- buckets: whether the problem is bursty or persistent\n",
        body_ja: "これは何か\nストレージやファイルシステム競合を読むための IO 停滞時間グループ記事です。\n\nなぜ重要か\nIO停滞の尾部は、ストレージが詰まっていることを利用者視点で示します。\n\nどう読むか\n- count: サンプル数\n- max: 最悪の停滞窓\n- buckets: バーストか持続か\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "io stall min",
                label_ja: "IO停滞 最小",
                source: "pressure",
                field: "ioStallMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "io stall max",
                label_ja: "IO停滞 最大",
                source: "pressure",
                field: "ioStallMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "io stall count",
                label_ja: "IO停滞 件数",
                source: "pressure",
                field: "ioStallCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "vmstat.major_fault_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "Major Fault Distribution",
        title_ja: "大規模ページフォールト分布",
        body_en: "What is this?\nA grouped article for major page fault counts, useful for spotting disk-backed memory demand.\n\nWhy it matters\nMajor faults cause synchronous disk reads and can amplify latency under load.\n\nHow to read\n- count: fault volume\n- max: worst burst\n- buckets: whether faults are clustered in a few phases\n",
        body_ja: "これは何か\n大規模ページフォールト回数を読むためのグループ記事です。ディスク依存のメモリ需要を見つけるのに役立ちます。\n\nなぜ重要か\nMajor fault は同期的なディスク読み込みを発生させ、負荷時の遅延を増幅します。\n\nどう読むか\n- count: フォールト量\n- max: 最悪バースト\n- buckets: 特定局面に集中しているか\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "major faults min",
                label_ja: "大規模フォールト 最小",
                source: "vmstat",
                field: "pgmajfaultMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "major faults max",
                label_ja: "大規模フォールト 最大",
                source: "vmstat",
                field: "pgmajfaultMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "major faults count",
                label_ja: "大規模フォールト 件数",
                source: "vmstat",
                field: "pgmajfaultCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "vmstat.page_reclaim_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "Page Reclaim Distribution",
        title_ja: "ページ回収分布",
        body_en: "What is this?\nA grouped article for reclaim activity, especially when the kernel starts reclaiming aggressively.\n\nWhy it matters\nThe shape of reclaim activity tells you whether memory pressure is manageable or spiraling.\n\nHow to read\n- count: sample count\n- max: worst reclaim burst\n- buckets: whether reclaim is smooth or sawtooth\n",
        body_ja: "これは何か\nカーネルが強めに回収を始めたときの reclaim 活動を読むためのグループ記事です。\n\nなぜ重要か\n回収活動の形を見ると、メモリ圧力が制御可能か悪化中か分かります。\n\nどう読むか\n- count: サンプル数\n- max: 最悪の回収バースト\n- buckets: 滑らかか鋸歯状か\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "page reclaim min",
                label_ja: "ページ回収 最小",
                source: "vmstat",
                field: "pageReclaimMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "page reclaim max",
                label_ja: "ページ回収 最大",
                source: "vmstat",
                field: "pageReclaimMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "page reclaim count",
                label_ja: "ページ回収 件数",
                source: "vmstat",
                field: "pageReclaimCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "proc/stat.context_switch_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "Process Context Switch Distribution",
        title_ja: "プロセスコンテキストスイッチ分布",
        body_en: "What is this?\nA grouped article for process-level context switch spread, useful when one workload is churning too much.\n\nWhy it matters\nA heavy distribution can indicate lock contention, wakeup storms, or overly chatty polling loops.\n\nHow to read\n- count: total samples\n- max: peak switching burst\n- min: quiet floor\n",
        body_ja: "これは何か\nプロセス単位のコンテキストスイッチ分布を読むためのグループ記事です。特定ワークロードが過剰に揺れているときに有効です。\n\nなぜ重要か\n分布が重いと、ロック競合、起床ストーム、細かすぎるポーリングの可能性があります。\n\nどう読むか\n- count: 総サンプル数\n- max: ピーク切り替えバースト\n- min: 静かな下限\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "proc ctxsw min",
                label_ja: "プロセスCTXSW 最小",
                source: "stat",
                field: "procContextSwitchMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "proc ctxsw max",
                label_ja: "プロセスCTXSW 最大",
                source: "stat",
                field: "procContextSwitchMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "proc ctxsw count",
                label_ja: "プロセスCTXSW 件数",
                source: "stat",
                field: "procContextSwitchCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "proc/stat.cpu_time_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "CPU Time Distribution",
        title_ja: "CPU時間分布",
        body_en: "What is this?\nA grouped article for CPU time samples and bucketed runtime classes.\n\nWhy it matters\nA stretched CPU time distribution suggests mixed workloads or uneven scheduling.\n\nHow to read\n- count: number of samples\n- max: hottest runtime slice\n- buckets: whether the workload is bimodal or smooth\n",
        body_ja: "これは何か\nCPU時間サンプルとバケット化された実行時間クラスを読むためのグループ記事です。\n\nなぜ重要か\nCPU時間の分布が伸びると、ワークロードの混在やスケジューリングの偏りが疑われます。\n\nどう読むか\n- count: サンプル数\n- max: 最も重い実行スライス\n- buckets: 二峰性か滑らかか\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "cpu time min",
                label_ja: "CPU時間 最小",
                source: "stat",
                field: "cpuTimeMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "cpu time max",
                label_ja: "CPU時間 最大",
                source: "stat",
                field: "cpuTimeMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "cpu time count",
                label_ja: "CPU時間 件数",
                source: "stat",
                field: "cpuTimeCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "proc/loadavg.runnable_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "Runnable Load Distribution",
        title_ja: "実行可能負荷分布",
        body_en: "What is this?\nA grouped article for runnable task pressure and load distribution around the scheduler.\n\nWhy it matters\nRunnable load that stays high means the machine is busy, not just occupied.\n\nHow to read\n- count: samples collected\n- max: worst contention window\n- buckets: whether load is spiky or sustained\n",
        body_ja: "これは何か\nスケジューラ周辺の実行可能タスク圧力と負荷分布を読むためのグループ記事です。\n\nなぜ重要か\n実行可能負荷が高止まりするなら、単に稼働中ではなく、詰まっている可能性があります。\n\nどう読むか\n- count: 収集したサンプル数\n- max: 最悪の競合窓\n- buckets: スパイク型か持続型か\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "runnable load min",
                label_ja: "実行可能負荷 最小",
                source: "loadavg",
                field: "runnableLoadMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "runnable load max",
                label_ja: "実行可能負荷 最大",
                source: "loadavg",
                field: "runnableLoadMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "runnable load count",
                label_ja: "実行可能負荷 件数",
                source: "loadavg",
                field: "runnableLoadCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "proc/softirqs.softirq_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "SoftIRQ Distribution",
        title_ja: "SoftIRQ分布",
        body_en: "What is this?\nA grouped article for softirq activity classes, useful for seeing interrupt handling bursts.\n\nWhy it matters\nSoftirq spikes can correlate with network floods, storage completion storms, or CPU imbalance.\n\nHow to read\n- count: event volume\n- max: worst burst\n- buckets: whether activity is narrow or broad\n",
        body_ja: "これは何か\nSoftIRQ 活動クラスを読むためのグループ記事です。割り込み処理のバースト把握に使います。\n\nなぜ重要か\nSoftIRQ のスパイクは、ネットワーク洪水、ストレージ完了ストーム、CPU不均衡と関連します。\n\nどう読むか\n- count: イベント量\n- max: 最悪のバースト\n- buckets: 範囲が狭いか広いか\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "softirq min",
                label_ja: "SoftIRQ 最小",
                source: "softirqs",
                field: "softirqMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "softirq max",
                label_ja: "SoftIRQ 最大",
                source: "softirqs",
                field: "softirqMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "softirq count",
                label_ja: "SoftIRQ 件数",
                source: "softirqs",
                field: "softirqCount",
            },
        ],
    },
    crate::article::EducationArticle {
        id: "proc/interrupts.irq_distribution",
        kind: crate::article::ArticleKind::Group,
        title_en: "IRQ Distribution",
        title_ja: "IRQ分布",
        body_en: "What is this?\nA grouped article for hard interrupt counts and their spread across observation windows.\n\nWhy it matters\nUneven IRQ distributions can point to device hot spots, affinity problems, or noisy hardware.\n\nHow to read\n- count: total samples\n- max: peak IRQ burst\n- min: quiet baseline\n",
        body_ja: "これは何か\nハード割り込み回数と観測窓ごとの広がりを読むためのグループ記事です。\n\nなぜ重要か\nIRQ 分布の偏りは、デバイスのホットスポット、アフィニティ問題、ノイジーなハードウェアを示すことがあります。\n\nどう読むか\n- count: 総サンプル数\n- max: ピークIRQバースト\n- min: 静かな基準\n",
        links: &[
            crate::article::ArticleLink::Metric {
                label_en: "irq min",
                label_ja: "IRQ 最小",
                source: "interrupts",
                field: "irqMin",
            },
            crate::article::ArticleLink::Metric {
                label_en: "irq max",
                label_ja: "IRQ 最大",
                source: "interrupts",
                field: "irqMax",
            },
            crate::article::ArticleLink::Metric {
                label_en: "irq count",
                label_ja: "IRQ 件数",
                source: "interrupts",
                field: "irqCount",
            },
        ],
    },
];
