use super::{Field, FieldValue, ProcEntry};
use std::fs;

pub fn parse() -> anyhow::Result<ProcEntry> {
    let content = fs::read_to_string("/proc/net/netstat")?;
    let mut fields = Vec::new();
    let lines: Vec<&str> = content.lines().collect();

    // Same format as /proc/net/snmp: pairs of header + value lines
    let mut i = 0;
    while i + 1 < lines.len() {
        let header_parts: Vec<&str> = lines[i].split_whitespace().collect();
        let value_parts: Vec<&str> = lines[i + 1].split_whitespace().collect();

        if header_parts.len() == value_parts.len() && header_parts.len() >= 2 {
            let category = header_parts[0].trim_end_matches(':');
            for j in 1..header_parts.len() {
                let val: i64 = value_parts[j].parse().unwrap_or(0);
                let field_name = format!("{}_{}", category, header_parts[j]);
                let description = describe_netstat_field(category, header_parts[j]);
                fields.push(Field {
                    name: field_name,
                    value: FieldValue::Integer(val),
                    unit: None,
                    description,
                });
            }
        }
        i += 2;
    }

    Ok(ProcEntry {
        source: "/proc/net/netstat".into(),
        fields,
    })
}

fn describe_netstat_field(category: &str, field: &str) -> String {
    match (category, field) {
        // --- TcpExt ---
        ("TcpExt", "SyncookiesSent") => "TCP SYN cookies sent (SYN flood protection)".into(),
        ("TcpExt", "SyncookiesRecv") => "TCP SYN cookies received".into(),
        ("TcpExt", "SyncookiesFailed") => "Invalid TCP SYN cookies received".into(),
        ("TcpExt", "EmbryonicRsts") => "RSTs received for embryonic (SYN_RECV) connections".into(),
        ("TcpExt", "PruneCalled") => "Times socket buffer memory pruning was called".into(),
        ("TcpExt", "RcvPruned") => "Packets pruned from receive queue due to memory pressure".into(),
        ("TcpExt", "OfoPruned") => "Packets pruned from out-of-order queue".into(),
        ("TcpExt", "OutOfWindowIcmps") => "ICMP messages dropped because they were out of window".into(),
        ("TcpExt", "LockDroppedIcmps") => "ICMP messages dropped because socket was locked".into(),
        ("TcpExt", "ArpFilter") => "Packets filtered by ARP filter".into(),
        ("TcpExt", "TW") => "TIME-WAIT sockets recycled by timeout".into(),
        ("TcpExt", "TWRecycled") => "TIME-WAIT sockets recycled by timestamp".into(),
        ("TcpExt", "TWKilled") => "TIME-WAIT sockets destroyed".into(),
        ("TcpExt", "PAWSActive") => "Active connections rejected by PAWS (Protection Against Wrapped Sequences)".into(),
        ("TcpExt", "PAWSEstab") => "Established connections packets rejected by PAWS".into(),
        ("TcpExt", "DelayedACKs") => "Delayed ACKs sent".into(),
        ("TcpExt", "DelayedACKLocked") => "Delayed ACKs further delayed because socket was locked".into(),
        ("TcpExt", "DelayedACKLost") => "Quick ACK mode activated due to delayed ACK loss".into(),
        ("TcpExt", "ListenOverflows") => "Times listen queue overflowed".into(),
        ("TcpExt", "ListenDrops") => "SYNs dropped due to listen queue full".into(),
        ("TcpExt", "TCPHPHits") => "TCP header prediction hits (fast-path packet processing)".into(),
        ("TcpExt", "TCPPureAcks") => "Pure ACKs received (no data)".into(),
        ("TcpExt", "TCPHPAcks") => "ACKs received via header prediction fast path".into(),
        ("TcpExt", "TCPRenoRecovery") => "TCP recoveries using Reno fast recovery".into(),
        ("TcpExt", "TCPSackRecovery") => "TCP recoveries using SACK".into(),
        ("TcpExt", "TCPSACKReneging") => "SACK data the receiver reneged on".into(),
        ("TcpExt", "TCPSACKReorder") => "Reordering events detected via SACK".into(),
        ("TcpExt", "TCPRenoReorder") => "Reordering events detected via Reno fast retransmit".into(),
        ("TcpExt", "TCPTSReorder") => "Reordering events detected via timestamp".into(),
        ("TcpExt", "TCPFullUndo") => "Full undo after spurious congestion detection".into(),
        ("TcpExt", "TCPPartialUndo") => "Partial undo after spurious congestion detection".into(),
        ("TcpExt", "TCPDSACKUndo") => "Undo after DSACK-detected spurious retransmission".into(),
        ("TcpExt", "TCPLossUndo") => "Undo after loss detection was found spurious".into(),
        ("TcpExt", "TCPLostRetransmit") => "Retransmitted segments that were lost again".into(),
        ("TcpExt", "TCPRenoFailures") => "Reno recovery failures".into(),
        ("TcpExt", "TCPSackFailures") => "SACK recovery failures".into(),
        ("TcpExt", "TCPLossFailures") => "Loss recovery failures".into(),
        ("TcpExt", "TCPFastRetrans") => "TCP fast retransmits".into(),
        ("TcpExt", "TCPSlowStartRetrans") => "Retransmits in slow start".into(),
        ("TcpExt", "TCPTimeouts") => "TCP connection timeouts".into(),
        ("TcpExt", "TCPLossProbes") => "TCP loss probes sent (TLP)".into(),
        ("TcpExt", "TCPLossProbeRecovery") => "Recoveries triggered by loss probes".into(),
        ("TcpExt", "TCPRenoRecoveryFail") => "Reno recovery failures (entered recovery but failed)".into(),
        ("TcpExt", "TCPSackRecoveryFail") => "SACK recovery failures (entered recovery but failed)".into(),
        ("TcpExt", "TCPRcvCollapsed") => "Packets collapsed in receive queue (memory pressure)".into(),
        ("TcpExt", "TCPBacklogCoalesce") => "Packets coalesced in socket backlog".into(),
        ("TcpExt", "TCPDSACKOldSent") => "DSACK sent for old (already received) data".into(),
        ("TcpExt", "TCPDSACKOfoSent") => "DSACK sent for out-of-order data".into(),
        ("TcpExt", "TCPDSACKRecv") => "DSACKs received".into(),
        ("TcpExt", "TCPDSACKOfoRecv") => "DSACKs received for out-of-order segments".into(),
        ("TcpExt", "TCPAbortOnData") => "Connections aborted due to data in close".into(),
        ("TcpExt", "TCPAbortOnClose") => "Connections aborted by close with data pending".into(),
        ("TcpExt", "TCPAbortOnMemory") => "Connections aborted due to memory pressure".into(),
        ("TcpExt", "TCPAbortOnTimeout") => "Connections aborted due to timeout".into(),
        ("TcpExt", "TCPAbortOnLinger") => "Connections aborted after linger timeout".into(),
        ("TcpExt", "TCPAbortFailed") => "Failed attempts to abort a connection".into(),
        ("TcpExt", "TCPMemoryPressures") => "Times socket entered TCP memory pressure".into(),
        ("TcpExt", "TCPMemoryPressuresChrono") => "Duration of TCP memory pressure in ms".into(),
        ("TcpExt", "TCPSACKDiscard") => "SACK blocks discarded".into(),
        ("TcpExt", "TCPDSACKIgnoredOld") => "DSACK blocks ignored (old)".into(),
        ("TcpExt", "TCPDSACKIgnoredNoUndo") => "DSACK blocks ignored (no undo)".into(),
        ("TcpExt", "TCPSpuriousRTOs") => "Spurious retransmission timeouts detected".into(),
        ("TcpExt", "TCPMD5NotFound") => "TCP segments with expected but missing MD5 signature".into(),
        ("TcpExt", "TCPMD5Unexpected") => "TCP segments with unexpected MD5 signature".into(),
        ("TcpExt", "TCPMD5Failure") => "TCP segments with failed MD5 signature check".into(),
        ("TcpExt", "TCPSackShifted") => "SACK data shifted in retransmit queue".into(),
        ("TcpExt", "TCPSackMerged") => "SACK blocks merged in retransmit queue".into(),
        ("TcpExt", "TCPSackShiftFallback") => "SACK shift fallbacks to traditional processing".into(),
        ("TcpExt", "TCPBacklogDrop") => "Segments dropped from socket backlog".into(),
        ("TcpExt", "PFMemallocDrop") => "Segments dropped in pfmemalloc context".into(),
        ("TcpExt", "TCPMinTTLDrop") => "Segments dropped below minimum TTL threshold".into(),
        ("TcpExt", "TCPDeferAcceptDrop") => "Segments dropped with TCP_DEFER_ACCEPT set".into(),
        ("TcpExt", "IPReversePathFilter") => "Packets dropped by reverse path filter".into(),
        ("TcpExt", "TCPTimeWaitOverflow") => "TIME-WAIT bucket overflows".into(),
        ("TcpExt", "TCPReqQFullDoCookies") => "Times SYN cookies were used due to full request queue".into(),
        ("TcpExt", "TCPReqQFullDrop") => "SYNs dropped because request queue was full".into(),
        ("TcpExt", "TCPRetransFail") => "Failed retransmit attempts".into(),
        ("TcpExt", "TCPRcvCoalesce") => "Segments coalesced in receive queue".into(),
        ("TcpExt", "TCPOFOQueue") => "Packets queued in out-of-order queue".into(),
        ("TcpExt", "TCPOFODrop") => "Packets dropped from out-of-order queue".into(),
        ("TcpExt", "TCPOFOMerge") => "Packets merged in out-of-order queue".into(),
        ("TcpExt", "TCPChallengeACK") => "Challenge ACKs sent (RFC 5961)".into(),
        ("TcpExt", "TCPSYNChallenge") => "SYN segments that triggered challenge ACKs".into(),
        ("TcpExt", "TCPFastOpenActive") => "TCP Fast Open connections initiated".into(),
        ("TcpExt", "TCPFastOpenActiveFail") => "Failed TCP Fast Open connection attempts".into(),
        ("TcpExt", "TCPFastOpenPassive") => "TCP Fast Open connections accepted".into(),
        ("TcpExt", "TCPFastOpenPassiveFail") => "Failed TCP Fast Open accept attempts".into(),
        ("TcpExt", "TCPFastOpenListenOverflow") => "TCP Fast Open requests dropped due to listen queue overflow".into(),
        ("TcpExt", "TCPFastOpenCookieReqd") => "TCP Fast Open SYNs requiring a cookie".into(),
        ("TcpExt", "TCPFastOpenBlackhole") => "TCP Fast Open blackhole events detected".into(),
        ("TcpExt", "TCPSpuriousRtxHostQueues") => "Spurious retransmits caused by host queues".into(),
        ("TcpExt", "BusyPollRxPackets") => "Packets received via busy polling".into(),
        ("TcpExt", "TCPAutoCorking") => "Times TCP auto-corking was applied".into(),
        ("TcpExt", "TCPFromZeroWindowAdv") => "Transitions from zero-window to non-zero".into(),
        ("TcpExt", "TCPToZeroWindowAdv") => "Transitions from non-zero window to zero-window".into(),
        ("TcpExt", "TCPWantZeroWindowAdv") => "Times zero-window advertisement was wanted".into(),
        ("TcpExt", "TCPSynRetrans") => "SYN-ACK retransmits (server-side)".into(),
        ("TcpExt", "TCPOrigDataSent") => "Original data segments sent (excluding retransmits)".into(),
        ("TcpExt", "TCPHystartTrainDetect") => "Hystart training phase congestion detections".into(),
        ("TcpExt", "TCPHystartTrainCwnd") => "Hystart congestion window at training detection".into(),
        ("TcpExt", "TCPHystartDelayDetect") => "Hystart delay-based congestion detections".into(),
        ("TcpExt", "TCPHystartDelayCwnd") => "Hystart congestion window at delay detection".into(),
        ("TcpExt", "TCPACKSkippedSynRecv") => "ACKs skipped in SYN-RECV state".into(),
        ("TcpExt", "TCPACKSkippedPAWS") => "ACKs skipped by PAWS check".into(),
        ("TcpExt", "TCPACKSkippedSeq") => "ACKs skipped due to sequence mismatch".into(),
        ("TcpExt", "TCPACKSkippedFinWait2") => "ACKs skipped in FIN-WAIT-2 state".into(),
        ("TcpExt", "TCPACKSkippedTimeWait") => "ACKs skipped in TIME-WAIT state".into(),
        ("TcpExt", "TCPACKSkippedChallenge") => "ACKs skipped by challenge ACK processing".into(),
        ("TcpExt", "TCPWinProbe") => "TCP window probes sent".into(),
        ("TcpExt", "TCPKeepAlive") => "TCP keepalive probes sent".into(),
        ("TcpExt", "TCPMTUPFail") => "TCP MTU path discovery failures".into(),
        ("TcpExt", "TCPMTUPSuccess") => "TCP MTU path discovery successes".into(),
        ("TcpExt", "TCPDelivered") => "TCP segments delivered to application (including retransmits)".into(),
        ("TcpExt", "TCPDeliveredCE") => "TCP segments delivered with ECN CE mark".into(),
        ("TcpExt", "TCPAckCompressed") => "Compressed ACKs sent (GRO)".into(),
        ("TcpExt", "TCPZeroWindowDrop") => "Segments dropped due to zero receive window".into(),
        ("TcpExt", "TCPRcvQDrop") => "Segments dropped from receive queue".into(),
        ("TcpExt", "TCPWqueueTooBig") => "Times write queue exceeded limit".into(),
        ("TcpExt", "TCPFastOpenPassiveAltKey") => "TCP Fast Open passive connections using alternate key".into(),

        // --- IpExt ---
        ("IpExt", "InNoRoutes") => "Inbound packets dropped due to no route".into(),
        ("IpExt", "InTruncatedPkts") => "Inbound packets dropped because they were truncated".into(),
        ("IpExt", "InMcastPkts") => "Multicast packets received".into(),
        ("IpExt", "OutMcastPkts") => "Multicast packets sent".into(),
        ("IpExt", "InBcastPkts") => "Broadcast packets received".into(),
        ("IpExt", "OutBcastPkts") => "Broadcast packets sent".into(),
        ("IpExt", "InOctets") => "Total bytes received (including headers)".into(),
        ("IpExt", "OutOctets") => "Total bytes sent (including headers)".into(),
        ("IpExt", "InMcastOctets") => "Multicast bytes received".into(),
        ("IpExt", "OutMcastOctets") => "Multicast bytes sent".into(),
        ("IpExt", "InBcastOctets") => "Broadcast bytes received".into(),
        ("IpExt", "OutBcastOctets") => "Broadcast bytes sent".into(),
        ("IpExt", "InCsumErrors") => "Inbound packets with checksum errors".into(),
        ("IpExt", "InNoECTPkts") => "Inbound packets with no ECN-Capable Transport flag".into(),
        ("IpExt", "InECT1Pkts") => "Inbound packets with ECT(1) flag set".into(),
        ("IpExt", "InECT0Pkts") => "Inbound packets with ECT(0) flag set".into(),
        ("IpExt", "InCEPkts") => "Inbound packets with ECN Congestion Experienced flag".into(),
        ("IpExt", "ReasmOverlaps") => "IP reassembly overlapping fragments detected".into(),

        // --- MPTcpExt (if present) ---
        ("MPTcpExt", "MPCapableSYNRX") => "MPTCP capable SYN segments received".into(),
        ("MPTcpExt", "MPCapableSYNTX") => "MPTCP capable SYN segments sent".into(),
        ("MPTcpExt", "MPCapableSYNACKRX") => "MPTCP capable SYN-ACK segments received".into(),
        ("MPTcpExt", "MPCapableACKRX") => "MPTCP capable ACK segments received".into(),
        ("MPTcpExt", "MPCapableFallbackACK") => "MPTCP fallback to regular TCP on ACK".into(),
        ("MPTcpExt", "MPCapableFallbackSYNACK") => "MPTCP fallback to regular TCP on SYN-ACK".into(),
        ("MPTcpExt", "MPFallbackTokenInit") => "MPTCP token init fallback events".into(),
        ("MPTcpExt", "MPTCPRetrans") => "MPTCP segments retransmitted".into(),
        ("MPTcpExt", "MPJoinNoTokenFound") => "MPTCP join requests with no token found".into(),
        ("MPTcpExt", "MPJoinSynRx") => "MPTCP join SYN segments received".into(),
        ("MPTcpExt", "MPJoinSynAckRx") => "MPTCP join SYN-ACK segments received".into(),
        ("MPTcpExt", "MPJoinSynAckHMacFailure") => "MPTCP join SYN-ACK HMAC validation failures".into(),
        ("MPTcpExt", "MPJoinAckRx") => "MPTCP join ACK segments received".into(),
        ("MPTcpExt", "MPJoinAckHMacFailure") => "MPTCP join ACK HMAC validation failures".into(),
        ("MPTcpExt", "DSSNotMatching") => "MPTCP DSS segments not matching".into(),
        ("MPTcpExt", "InfiniteMapRx") => "MPTCP infinite map segments received".into(),
        ("MPTcpExt", "OFOQueueTail") => "MPTCP out-of-order queue tail additions".into(),
        ("MPTcpExt", "OFOQueue") => "MPTCP segments queued out-of-order".into(),
        ("MPTcpExt", "OFOMerge") => "MPTCP out-of-order segments merged".into(),
        ("MPTcpExt", "NoDSSInWindow") => "MPTCP segments without DSS in window".into(),
        ("MPTcpExt", "DuplicateData") => "MPTCP duplicate data segments received".into(),
        ("MPTcpExt", "AddAddr") => "MPTCP ADD_ADDR options received".into(),
        ("MPTcpExt", "EchoAdd") => "MPTCP ADD_ADDR echo options sent".into(),
        ("MPTcpExt", "PortAdd") => "MPTCP port-based ADD_ADDR options received".into(),
        ("MPTcpExt", "MPJoinPortSynRx") => "MPTCP port-based join SYN segments received".into(),
        ("MPTcpExt", "MPJoinPortSynAckRx") => "MPTCP port-based join SYN-ACK segments received".into(),
        ("MPTcpExt", "MPJoinPortAckRx") => "MPTCP port-based join ACK segments received".into(),
        ("MPTcpExt", "MismatchPortSynRx") => "MPTCP join SYN segments with mismatched port".into(),
        ("MPTcpExt", "MismatchPortAckRx") => "MPTCP join ACK segments with mismatched port".into(),
        ("MPTcpExt", "RmAddr") => "MPTCP RM_ADDR options received".into(),
        ("MPTcpExt", "RmAddrDrop") => "MPTCP RM_ADDR options dropped".into(),
        ("MPTcpExt", "RmSubflow") => "MPTCP subflows removed".into(),
        ("MPTcpExt", "MPPrioTx") => "MPTCP MP_PRIO options sent".into(),
        ("MPTcpExt", "MPPrioRx") => "MPTCP MP_PRIO options received".into(),
        ("MPTcpExt", "MPFailTx") => "MPTCP MP_FAIL options sent".into(),
        ("MPTcpExt", "MPFailRx") => "MPTCP MP_FAIL options received".into(),
        ("MPTcpExt", "MPFastcloseTx") => "MPTCP MP_FASTCLOSE options sent".into(),
        ("MPTcpExt", "MPFastcloseRx") => "MPTCP MP_FASTCLOSE options received".into(),
        ("MPTcpExt", "MPRstTx") => "MPTCP MP_RST options sent".into(),
        ("MPTcpExt", "MPRstRx") => "MPTCP MP_RST options received".into(),
        ("MPTcpExt", "RcvPruned") => "MPTCP received data pruned".into(),
        ("MPTcpExt", "SubflowStale") => "MPTCP stale subflows detected".into(),
        ("MPTcpExt", "SubflowRecover") => "MPTCP stale subflows recovered".into(),
        ("MPTcpExt", "SndWndShared") => "MPTCP shared send window events".into(),
        ("MPTcpExt", "RcvWndShared") => "MPTCP shared receive window events".into(),
        ("MPTcpExt", "RcvWndConflictUpdate") => "MPTCP receive window conflict updates".into(),
        ("MPTcpExt", "RcvWndConflict") => "MPTCP receive window conflicts".into(),

        _ => format!("{}: {}", category, field),
    }
}
